# Generated by Django 5.1.4 on 2025-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
