# Generated by Django 5.1.4 on 2025-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
